spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: ******
      secret-key: ******
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: jiahemall

  application:
    name: jiahemall-third-party

server:
  port: 30000
