spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GH7o7AGhdbdLPuTQZ6M
      secret-key: GM2giB8tmtXqahAEKn278c3N1DoAB7
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: jiahemall

  application:
    name: jiahemall-third-party

server:
  port: 30000
